In [1]:
# importing libraries
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading data
house = pd.read_csv('house.csv')
print(house.shape)
print(house.columns)

(5802, 12)
Index(['TOTAL_VALUE', 'TAX', 'LOT_SQFT', 'GROSS_AREA', 'LIVING_AREA', 'FLOORS',
       'ROOMS', 'BEDROOMS', 'FULL_BATH', 'HALF_BATH', 'KITCHEN', 'FIREPLACE'],
      dtype='object')


In [3]:
house.head(20)

TOTAL_VALUE   TAX  LOT_SQFT  GROSS_AREA  LIVING_AREA  FLOORS  ROOMS  \
0         344.2  4330      9965        2436         1352     2.0      6   
1         412.6  5190      6590        3108         1976     2.0     10   
2         330.1  4152      7500        2294         1371     2.0      8   
3         498.6  6272     13773        5032         2608     1.0      9   
4         331.5  4170      5000        2370         1438     2.0      7   
5         337.4  4244      5142        2124         1060     1.0      6   
6         359.4  4521      5000        3220         1916     2.0      7   
7         320.4  4030     10000        2208         1200     1.0      6   
8         333.5  4195      6835        2582         1092     1.0      5   
9         409.4  5150      5093        4818         2992     2.0      8   
10        313.0  3937      5000        2624         1485     1.5      6   
11        344.5  4333      6768        2844         1460     1.5      6   
12        315.5  3968      5000        2196         1290     2.0      6   
13        575.0  7233     12288        4616         2378     2.0      9   
14        326.2  4103      5000        2536         1272     1.5      6   
15        298.2  3751      5000        2129          864     1.0      7   
16        313.1  3938      6949        2612         1438     1.5      7   
17        344.9  4338     10000        2099         1445     1.0      7   
18        330.7  4160      5000        2408         1470     2.0      7   
19        348.0  4377      9001        2840         1632     2.0      7   

    BEDROOMS  FULL_BATH  HALF_BATH  KITCHEN  FIREPLACE  
0          3          1          1        1          0  
1          4          2          1        1          0  
2          4          1          1        1          0  
3          5          1          1        1          1  
4          3          2          0        1          0  
5          3          1          0        1          1  
6          3          1          1        1          0  
7          3          1          0        1          0  
8          3          1          0        1          1  
9          4          2          0        1          0  
10         3          2          0        1          1  
11         3          2          0        1          1  
12         3          1          0        1          0  
13         4          2          1        1          1  
14         3          1          1        1          1  
15         3          2          0        1          0  
16         3          1          1        1          0  
17         3          1          1        1          1  
18         3          1          0        1          0  
19         3          1          0        1          0

In [4]:
# picking the predictors
var = ['TAX', 'FLOORS', 'ROOMS']
#choosing the predicted
dependent_variable = ['TOTAL_VALUE']

house_x= house[var] # independent variables
house_y= house[dependent_variable] #dependent varaible

In [5]:
print (house_x.shape)
print(house_y.shape)

(5802, 3)
(5802, 1)


In [6]:
house_y.columns

Index(['TOTAL_VALUE'], dtype='object')

In [7]:
#splitting the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train,y_test = train_test_split(house_x, house_y, test_size =0.3, random_state=42)
x_train.shape[0], x_test.shape[0]

(4061, 1741)

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()


In [9]:
#trainning the model 
model.fit(x_train, y_train)  

LinearRegression()

In [10]:
# Linear model coefficients
coefficents =model.coef_
coefficents

array([[ 0.07949157,  0.00028905, -0.00028666]])

In [11]:
#Linear model intercept
intercpt= model.intercept_
intercpt

array([0.03971078])

In [12]:
#The regression ststistical formular
#y = 0.0397 + 0.07949TAX+ 0.00029FLOORS-0.00029ROOMS

In [13]:
#predicting the test data
y_prediction_test = model.predict(x_test)
y_prediction_test.shape,y_prediction_test

((1741, 1),
 array([[306.31930765],
        [305.20642564],
        [239.22856522],
        ...,
        [297.41654061],
        [582.3932537 ],
        [383.58483159]]))

In [14]:
#predicting the value of a single home
my_house = [[5190, 2 ,10]]

model.predict(my_house)

array([[412.59868213]])

In [15]:
#r2 perfomance measurement
from sklearn.metrics import r2_score
r2_score(y_test, y_prediction_test)

0.9999999499089725

In [16]:
# mean absolute error perfomance measurement
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_prediction_test)

0.01973323924212563

In [18]:
#comparing the actual and predicted value
y_test, y_prediction_test

(      TOTAL_VALUE  y_prediction_test
 5070        306.3         306.319308
 1103        305.2         305.206426
 812         239.2         239.228565
 1632        396.5         396.462753
 1128        322.5         322.535591
 ...           ...                ...
 5648        356.8         356.796458
 5126        407.4         407.432590
 1338        297.4         297.416541
 3885        582.4         582.393254
 4269        383.6         383.584832
 
 [1741 rows x 2 columns],
 array([[306.31930765],
        [305.20642564],
        [239.22856522],
        ...,
        [297.41654061],
        [582.3932537 ],
        [383.58483159]]))